---
controller_templates:
  - name: EXERCISE / OS Update
    project: Project Leapp
    playbook: pkgs_full_update.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - rhel7
            - rhel8
            - rhel9
          required: true
  - name: EXERCISE / Analysis
    project: Project Leapp
    playbook: analysis.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - rhel7
            - rhel8
            - rhel9
          required: true
    extra_vars:
      leapp_upgrade_type: connected
      leapp_metadata_url: https://host.location/leapp-data-21.tar.gz
      leapp_repos_enabled: []
    ask_variables_on_launch: true
  - name: EXERCISE / Upgrade
    project: Project Leapp
    playbook: upgrade.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - rhel7
            - rhel8
            - rhel9
          required: true
    extra_vars:
      leapp_upgrade_type: connected
      leapp_repos_enabled: []
    ask_variables_on_launch: true
  - name: EXERCISE / Validate
    project: Project Leapp
    playbook: validation.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - rhel7
            - rhel8
            - rhel9
          required: true
  - name: EXERCISE / Remediation
    project: Project Leapp
    playbook: remediate.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - rhel7
            - rhel8
            - rhel9
          required: true
  - name: EXERCISE / Snapshot Instance
    project: Project Leapp
    playbook: snapshot_instance.yml
    inventory: Workshop Inventory
    limit: ansible-1
    credentials:
      - Workshop Credential
    extra_vars:
      snapshot: aws
      ec2_region: "{{ workshop_ec2_region }}"
      instances:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
  - name: EXERCISE / Snapshot Rollback
    project: Project Leapp
    playbook: snapshot_revert.yml
    inventory: Workshop Inventory
    limit: ansible-1
    credentials:
      - Workshop Credential
    extra_vars:
      snapshot: aws
      ec2_region: "{{ workshop_ec2_region }}"
      instances:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
      snapshots:
        tags:
          Workshop: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          Environment: leapp
  - name: UTILITY / Instance Details
    project: Project Leapp
    playbook: instance_details.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    extra_vars:
      ec2_region: "{{ workshop_ec2_region }}"
      instances:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
  - name: UTILITY / Update inventories via dynamic sources
    project: Project Leapp
    playbook: inventory_source_update.yml
    inventory: Workshop Inventory
    credentials:
      - Controller Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory to update
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - rhel7
            - rhel8
            - rhel9
          required: true
  - name: UTILITY / Fact Scan
    project: Project Leapp
    playbook: fact_scan.yml
    inventory: Workshop Inventory
    use_fact_cache: true
    credentials:
      - Workshop Credential
    extra_vars:
      _hosts: all
  - name: UTILITY / Set instance tags
    project: Project Leapp
    playbook: set_instance_tags.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory to update
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - rhel7
            - rhel8
            - rhel9
          required: true
...
