---
controller_workflows:
  - name: AUTO / 02 Upgrade
    description: Workflow for Snapshot and Leapp Upgrade
    # extra_vars:
    #   var_name: value
    inventory: Workshop Inventory
    state: present
    organization: Default
    survey_enabled: true
    survey_spec:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    simplified_workflow_nodes:
      - identifier: UTILITY / Snapshot Instance
        unified_job_template: UTILITY / Snapshot Instance
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - AUTO / Upgrade
      - identifier: AUTO / Upgrade
        unified_job_template: AUTO / Upgrade
        organization: Default
        all_parents_must_converge: false
        success_nodes: []
...
