---
- name: Analysis
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  tasks:
    - name: Generate preupgrade analysis report
      block:
        - name: Run RIPU preupg
          ansible.builtin.import_role:
            name: infra.leapp.analysis
...
