---
- name: Wait for connection...
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Configure yum system releasever
  ansible.builtin.copy:
    content: "{{ yum_system_releasever | default(8.8) }}"
    dest: "/etc/yum/vars/releasever"
    owner: root
    group: root
    mode: '0644'

- name: Clearing yum cache...
  ansible.builtin.command: >-
    yum clean all
...
