---
- name: Wait for connection...
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Define kernel modules to unload
  ansible.builtin.set_fact:
    kernel_modules_to_unload:
      - floppy
      - pata_acpi

- name: Kernel modules defined by kernel_modules_to_unload are unloaded
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ kernel_modules_to_unload }}"

- name: Remove pam_pkcs11 module # noqa command-instead-of-module
  ansible.builtin.shell: |
    set -o pipefail
    leapp answer --section remove_pam_pkcs11_module_check.confirm=True
  args:
    executable: /bin/bash

- name: Configure sshd
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "prohibit-password" }
    - { key: "PasswordAuthentication", value: "no" }
  notify:
    - Restart sshd

- name: Enable yum plugins globally in /etc/yum.conf
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    line: 'plugins=1'
    regexp: '^plugins='

- name: Read the subscription-manager.conf file
  shell: cat /etc/yum/pluginconf.d/subscription-manager.conf
  register: file_content

- name: Check if enable=1 is present in the file
  set_fact:
    enable_present: "{{ file_content.stdout | regex_search('enable=1') }}"

- name: Replace enable=0 with enable=1 if not present
  replace:
    path: /etc/yum/pluginconf.d/subscription-manager.conf
    regexp: 'enable=0'
    replace: 'enable=1'
  when: not enable_present

- name: Execute chattr command
  ansible.builtin.command: chattr -i /boot/grub2/grub.cfg

- name: Execute chattr command
  ansible.builtin.command: chattr -i /etc/passwd
...
