---
- name: Roleback
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  tasks:
    - name: Perform instance snapshot rollback
      block:
        - name: Snapshot rollback
          ansible.builtin.import_role:
            name: heatmiser.ansible_snapshot.aws

# always:
#   - name: Clean up
#     ansible.builtin.import_role:
#       name: logging
#       tasks_from: clean_up.yml
...
