---
- name: Set Instance_Id tag for combination merge
  ansible.builtin.set_fact:
    snapshots_combine:
      tags:
        Instance_id: "{{ instance_id }}"

- name: Combine snapshot Instance_Id tag with existing snapshots definition
  ansible.builtin.set_fact:
    snapshots: "{{ snapshots | ansible.builtin.combine(snapshots_combine, recursive=true) }}"

- name: Debug output - snapshots
  ansible.builtin.debug:
    msg: "{{ snapshots }}"

- name: "Get snapshot details"
  ansible.builtin.include_role:
    name: heatmiser.ansible_snapshot.aws
    tasks_from: snapshot/get_snapshot_details

- name: Revert snapshot of instance
  ansible.builtin.include_role:
    name: heatmiser.ansible_snapshot.aws
...
