---
- name: Set instance tag
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  gather_facts: true
  vars:
    instances: "{{ instances_template }}"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Primary playbook loop over ansible_play_hosts
      ansible.builtin.include_tasks: set_instance_tags_incl.yml
...
