---
- name: Get instance details - amazon.aws.ec2_instance_info
  hosts: "{{ all | default('control[0]') }}"
  connection: local
  gather_facts: false
  tasks:
    - name: "Get instance details"
      ansible.builtin.include_role:
        name: infra.leapp.snapshot
        tasks_from: aws/get_instance_details

    - name: Debug - instance_details via amazon.aws.ec2_instance_info
      ansible.builtin.debug:
        msg: "{{ instance_details.instances | selectattr('tags.os_major_version', 'defined') }}"

    - name: Initialize list vars
      ansible.builtin.set_fact:
        # host_distribution_major_version: "{{ instance_details.instances | selectattr('tags.os_major_version', 'defined') | map(attribute='tags.os_major_version') }}"
        host_distribution_major_version: "{{ instance_details.instances | selectattr('tags.os_major_version', 'equalto', rhel_inventory_group.split('rhel')[1]) | map(attribute='tags.os_major_version') }}"
        host_short_name: "{{ instance_details.instances | selectattr('tags.os_major_version', 'equalto', rhel_inventory_group.split('rhel')[1]) | map(attribute='tags.short_name') }}"
        host_ec2_instance_id: "{{ instance_details.instances | selectattr('tags.os_major_version', 'equalto', rhel_inventory_group.split('rhel')[1]) | map(attribute='instance_id') }}"

    - name: Debug - host_distribution_major_version and host_ec2_instance_id and more
      ansible.builtin.debug:
        msg:
          - "{{ host_distribution_major_version }}"
          - "{{ host_short_name }}"
          - "{{ host_ec2_instance_id }}"

- name: Get instance ansible facts
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: Wait for connection...and gather facts
      ansible.builtin.setup:
        gather_timeout: 120
      register: instance_facts
      ignore_errors: true
      until: "instance_facts is not failed"
      retries: 10
      delay: 10

    - name: Share instance_details facts from ansible-1 among all hosts
      ansible.builtin.set_fact:
        instance_details: "{{ hostvars['ansible-1']['instance_details'] }}"
      run_once: true

    - name: Debug - instance_details via amazon.aws.ec2_instance_info
      ansible.builtin.debug:
        msg:
          - "host_distribution_major_version: {{ instance_details.instances | selectattr('tags.os_major_version', 'equalto', rhel_inventory_group.split('rhel')[1]) | map(attribute='tags.os_major_version') }}"
          - "host_short_name: {{ instance_details.instances | selectattr('tags.os_major_version', 'equalto', rhel_inventory_group.split('rhel')[1]) | map(attribute='tags.short_name') }}"
          - "host_ec2_instance_id: {{ instance_details.instances | selectattr('tags.os_major_version', 'equalto', rhel_inventory_group.split('rhel')[1]) | map(attribute='instance_id') }}"
      run_once: true

    - name: Debug - instance_facts via ansible
      ansible.builtin.debug:
        msg: "{{ instance_facts }}"
...
