---
- name: Take snapshot of instance
  hosts: "{{ 'control[0]' | default(omit) }}"
  connection: local
  gather_facts: false
  vars:
    ec2_instance_action: "snapshot_create"
  tasks:
    - name: Set instance tag os_major_version based on survey
      when: rhel_inventory_group != "ALL_rhel"
      block:
        - name: Set os_major_version tag for combination merge
          ansible.builtin.set_fact:
            instances_combine:
              tags:
                os_major_version: "{{ rhel_inventory_group | regex_replace('rhel') }}"

        - name: Combine instance extra_var tags with survey-based instance tag os_major_version
          ansible.builtin.set_fact:
            instances: "{{ instances_template | ansible.builtin.combine(instances_combine, recursive=true) }}"

    - name: "Get instance details"
      ansible.builtin.include_role:
        name: heatmiser.ansible_snapshot.aws
        tasks_from: instance/get_instance_details

    - name: Set snapshots variables from instances variables
      ansible.builtin.set_fact:
        snapshots:
          tags:
            Student: "{{ instances.tags.Student }}"
            guid: "{{ instances.tags.guid }}"
            Environment: leapp

    - name: Take snapshot of instance "{{ item.tags.short_name }}"
      ansible.builtin.include_role:
        name: heatmiser.ansible_snapshot.aws
...
