---
- name: Create/revert/remove/check LVM snapshots of node
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  become: yes
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    TERM: linux
  tasks:
    - name: "Execute snapshot check"
      ansible.builtin.include_role:
        name: "infra.lvm_snapshots.snapshot_create"
          # snapshot_* vars provided via AAP2 job template and associated surveys
      vars:
        snapshot_create_check_only: true
      when: lvm_snapshots_action == "check"

    - name: "Execute snapshot {{ lvm_snapshots_action }}"
      ansible.builtin.include_role:
        name: "infra.lvm_snapshots.snapshot_{{ lvm_snapshots_action }}"
          # snapshot_* vars provided via AAP2 job template and associated surveys
      when: (lvm_snapshots_action == "create") or (lvm_snapshots_action == "remove") or (lvm_snapshots_action == "revert")
...
