---
- name: Take snapshot of instance
  hosts: "{{ 'control[0]' | default(omit) }}"
  connection: local
  gather_facts: false
  tasks:
    - name: "Get instance details"
      ansible.builtin.include_role:
        name: infra.leapp.snapshot
        tasks_from: aws/get_instance_details

    - name: Set snapshots variables from instances variables
      ansible.builtin.set_fact:
        snapshots:
          tags:
            Student: "{{ instances.tags.Student }}"
            guid: "{{ instances.tags.guid }}"

    - name: "Get snapshot details"
      ansible.builtin.include_role:
        name: infra.leapp.snapshot
        tasks_from: aws/get_snapshot_details

    - name: Debug output - instance_details
      ansible.builtin.debug:
        msg: "{{ instance_details }}"

    - name: Debug output - snapshot_details
      ansible.builtin.debug:
        msg: "{{ snapshot_details }}"

    - name: Debug output - instance_details - map(attribute='instance_id')
      ansible.builtin.debug:
        msg:
          - "{{ instance_details.instances | map(attribute='instance_id') | list | unique }}"
          - "{{ snapshot_details.snapshots | map(attribute='tags.Instance_id') | list | unique }}"

    - name: Test match on presence of snapshot for instance
      ansible.builtin.debug:
        msg: "{{ item }} has a snapshot"
      # loop: "{{ instance_details.instances | map(attribute='instance_id') | list }}"
      when: item in snapshot_details.snapshots | map(attribute='tags.Instance_id') | list | unique
      loop: "{{ instance_details.instances | map(attribute='instance_id') | list | unique }}"
      # loop: "{{ snapshot_details.snapshots | map(attribute='tags.Instance_id') | list | selectattr('name', 'in', List1)|list }}"
...
