---
- name: SELinux mode is set to {{ selinux_mode }}
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_mode }}"
  register: selinux_results

- name: Reboot when required for SELinux change
  ansible.builtin.reboot:
    reboot_timeout: 7200
    post_reboot_delay: "{{ post_reboot_delay }}"
  timeout: 7260
  when: selinux_results.reboot_required

- name: Verify SELinux is set to {{ selinux_mode }}
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_mode }}"
  check_mode: true
  register: selinux_check_results
  failed_when: selinux_check_results.changed
...
